name: Establish And Publish A Docker Image For Production Deployment.

on:
    push:
        branches:
          - main

jobs:
    registry:
        name: Publish docker image to Yoth Container Registry
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the repository
            uses: actions/checkout@v3

          - name: Docker image metadata
            id: meta
            uses: docker/metadata-action@v4
            with:
                images: registry.yoth.dev/book:latest

          - name: Signin into Yoth Container Registry
            if: github.event_name == 'push'
            uses: docker/login-action@v2
            with:
                registry: registry.yoth.dev
                username: ${{ secrets.YOTH_REGISTRY_CLIENT }}
                password: ${{ secrets.YOTH_REGISTRY_SECRET }}

          - name: Build and push
            uses: docker/build-push-action@v4
            with:
                context: .
                push: ${{ github.event_name == 'push' }}
                tags: registry.yoth.dev/book:latest
                labels: ${{ steps.meta.outputs.labels }}

    ssh:
      name: Pull the image and restart container
      needs: "registry"
      runs-on: ubuntu-latest
      steps:
        - name: Executing commands
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.PRODUCTION_HOSTNAME }}
            username: ${{ secrets.PRODUCTION_USERNAME }}
            password: ${{ secrets.PRODUCTION_PASSWORD }}
            port: ${{ secrets.PRODUCTION_PORT }}
            script: sudo bash backend_deployment.sh
